[project]
name = "ainews"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "markdown2>=2.5.3",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "zhipu>=1.0.1",
    "zhipuai>=2.1.5.20250626",
]
